### ISSUE TITLE
Bug with Tensor Size Mismatch

### ISSUE THREAD

**Issue by xehu** [Watts-Lab/team_comm_tools#307]
Initializing Featurization...
Confirmed that data has conversation_id: gameId, speaker_id: sampleId and message: transcript columns!
ERROR: The length of the vector data does not match the length of the chat data. Regenerating...
Generating SBERT sentence vectors...
ERROR: The length of the sentiment data does not match the length of the chat data. Regenerating...
Generating RoBERTa sentiments...

stack trace:
{
	"name": "RuntimeError",
	"message": "The expanded size of the tensor (524) must match the existing size (514) at non-singleton dimension 1.  Target sizes: [1, 524].  Tensor sizes: [1, 514]",
	"stack": "---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[18], line 1
----> 1 transcript_featurizer = FeatureBuilder(
      2         input_df = uber_transcript[:5000],
      3         conversation_id_col = \"gameId\",
      4         speaker_id_col = \"sampleId\",
      5         message_col = \"transcript\",
      6         timestamp_col= (\"filepath_start\", \"filepath_end\"),
      7         # this is where we'll cache things like sentence vectors; this directory doesn't have to exist; we'll create it for you!
      8         vector_directory = f\"./vector_data/\",
      9         output_file_path_chat_level = f\"../data/chat_level_features.csv\",
     10         output_file_path_user_level = f\"../data/user_level_features.csv\",
     11         output_file_path_conv_level = f\"../data/conversation_level_features.csv\",
     12         
     13         turns = True, # if true, this will combine successive turns by the same speaker.
     14         # these features depend on sentence vectors, so they take longer to generate on larger datasets. Add them in manually if you are interested in adding them to your output!
     15            custom_features = [
     16                  \"(BERT) Mimicry\",
     17                  \"Moving Mimicry\",
     18                  \"Forward Flow\",
     19                  \"Discursive Diversity\"
     20            ],
     21         )
     23 # this line of code runs the FeatureBuilder on your data
     24 transcript_featurizer.featurize(col=\"transcript\")

File ~/github/contact-theory-topic/team_tools_env/lib/python3.11/site-packages/team_comm_tools/feature_builder.py:341, in FeatureBuilder.__init__(self, input_df, vector_directory, output_file_path_chat_level, output_file_path_user_level, output_file_path_conv_level, custom_features, analyze_first_pct, turns, conversation_id_col, speaker_id_col, message_col, timestamp_col, grouping_keys, cumulative_grouping, within_task, ner_training_df, ner_cutoff, regenerate_vectors)
    338     if(not need_sentiment and feature_dict[feature][\"bert_sentiment_data\"]):
    339         need_sentiment = True
--> 341 check_embeddings(self.chat_data, self.vect_path, self.bert_path, need_sentence, need_sentiment, self.regenerate_vectors, self.message_col)
    343 if(need_sentence):
    344     self.vect_data = pd.read_csv(self.vect_path, encoding='mac_roman')

File ~/github/contact-theory-topic/team_tools_env/lib/python3.11/site-packages/team_comm_tools/utils/check_embeddings.py:70, in check_embeddings(chat_data, vect_path, bert_path, need_sentence, need_sentiment, regenerate_vectors, message_col)
     68     if len(bert_df) != len(chat_data):
     69         print(\"ERROR: The length of the sentiment data does not match the length of the chat data. Regenerating...\")
---> 70         generate_bert(chat_data, bert_path, message_col)
     71 except FileNotFoundError:
     72     if need_sentiment: # It's OK if we don't have the path, if the sentiment features are not necessary

File ~/github/contact-theory-topic/team_tools_env/lib/python3.11/site-packages/team_comm_tools/utils/check_embeddings.py:206, in generate_bert(chat_data, output_path, message_col)
    203 print(f\"Generating RoBERTa sentiments...\")
    205 messages = chat_data[message_col]
--> 206 sentiments = messages.apply(get_sentiment)
    208 sent_arr = [list(dict.values()) for dict in sentiments]
    210 sent_df = pd.DataFrame(sent_arr, columns =['positive_bert', 'negative_bert', 'neutral_bert']) 

File ~/github/contact-theory-topic/team_tools_env/lib/python3.11/site-packages/pandas/core/series.py:4924, in Series.apply(self, func, convert_dtype, args, by_row, **kwargs)
   4789 def apply(
   4790     self,
   4791     func: AggFuncType,
   (...)
   4796     **kwargs,
   4797 ) -> DataFrame | Series:
   4798     \"\"\"
   4799     Invoke function on values of Series.
   4800 
   (...)
   4915     dtype: float64
   4916     \"\"\"
   4917     return SeriesApply(
   4918         self,
   4919         func,
   4920         convert_dtype=convert_dtype,
   4921         by_row=by_row,
   4922         args=args,
   4923         kwargs=kwargs,
-> 4924     ).apply()

File ~/github/contact-theory-topic/team_tools_env/lib/python3.11/site-packages/pandas/core/apply.py:1427, in SeriesApply.apply(self)
   1424     return self.apply_compat()
   1426 # self.func is Callable
-> 1427 return self.apply_standard()

File ~/github/contact-theory-topic/team_tools_env/lib/python3.11/site-packages/pandas/core/apply.py:1507, in SeriesApply.apply_standard(self)
   1501 # row-wise access
   1502 # apply doesn't have a `na_action` keyword and for backward compat reasons
   1503 # we need to give `na_action=\"ignore\"` for categorical data.
   1504 # TODO: remove the `na_action=\"ignore\"` when that default has been changed in
   1505 #  Categorical (GH51645).
   1506 action = \"ignore\" if isinstance(obj.dtype, CategoricalDtype) else None
-> 1507 mapped = obj._map_values(
   1508     mapper=curried, na_action=action, convert=self.convert_dtype
   1509 )
   1511 if len(mapped) and isinstance(mapped[0], ABCSeries):
   1512     # GH#43986 Need to do list(mapped) in order to get treated as nested
   1513     #  See also GH#25959 regarding EA support
   1514     return obj._constructor_expanddim(list(mapped), index=obj.index)

File ~/github/contact-theory-topic/team_tools_env/lib/python3.11/site-packages/pandas/core/base.py:921, in IndexOpsMixin._map_values(self, mapper, na_action, convert)
    918 if isinstance(arr, ExtensionArray):
    919     return arr.map(mapper, na_action=na_action)
--> 921 return algorithms.map_array(arr, mapper, na_action=na_action, convert=convert)

File ~/github/contact-theory-topic/team_tools_env/lib/python3.11/site-packages/pandas/core/algorithms.py:1743, in map_array(arr, mapper, na_action, convert)
   1741 values = arr.astype(object, copy=False)
   1742 if na_action is None:
-> 1743     return lib.map_infer(values, mapper, convert=convert)
   1744 else:
   1745     return lib.map_infer_mask(
   1746         values, mapper, mask=isna(values).view(np.uint8), convert=convert
   1747     )

File lib.pyx:2972, in pandas._libs.lib.map_infer()

File ~/github/contact-theory-topic/team_tools_env/lib/python3.11/site-packages/team_comm_tools/utils/check_embeddings.py:231, in get_sentiment(text)
    229 text = ' '.join(text.split()[:512]) # handle cases when the text is too long: just take the first 512 chars (hacky, but BERT context window cannot be changed)
    230 encoded = tokenizer(text, return_tensors='pt')
--> 231 output = model_bert(**encoded)
    233 scores = output[0][0].detach().numpy()
    234 scores = softmax(scores)

File ~/github/contact-theory-topic/team_tools_env/lib/python3.11/site-packages/torch/nn/modules/module.py:1553, in Module._wrapped_call_impl(self, *args, **kwargs)
   1551     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1552 else:
-> 1553     return self._call_impl(*args, **kwargs)

File ~/github/contact-theory-topic/team_tools_env/lib/python3.11/site-packages/torch/nn/modules/module.py:1562, in Module._call_impl(self, *args, **kwargs)
   1557 # If we don't have any hooks, we want to skip the rest of the logic in
   1558 # this function, and just call forward.
   1559 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1560         or _global_backward_pre_hooks or _global_backward_hooks
   1561         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1562     return forward_call(*args, **kwargs)
   1564 try:
   1565     result = None

File ~/github/contact-theory-topic/team_tools_env/lib/python3.11/site-packages/transformers/models/roberta/modeling_roberta.py:1195, in RobertaForSequenceClassification.forward(self, input_ids, attention_mask, token_type_ids, position_ids, head_mask, inputs_embeds, labels, output_attentions, output_hidden_states, return_dict)
   1187 r\"\"\"
   1188 labels (`torch.LongTensor` of shape `(batch_size,)`, *optional*):
   1189     Labels for computing the sequence classification/regression loss. Indices should be in `[0, ...,
   1190     config.num_labels - 1]`. If `config.num_labels == 1` a regression loss is computed (Mean-Square loss), If
   1191     `config.num_labels > 1` a classification loss is computed (Cross-Entropy).
   1192 \"\"\"
   1193 return_dict = return_dict if return_dict is not None else self.config.use_return_dict
-> 1195 outputs = self.roberta(
   1196     input_ids,
   1197     attention_mask=attention_mask,
   1198     token_type_ids=token_type_ids,
   1199     position_ids=position_ids,
   1200     head_mask=head_mask,
   1201     inputs_embeds=inputs_embeds,
   1202     output_attentions=output_attentions,
   1203     output_hidden_states=output_hidden_states,
   1204     return_dict=return_dict,
   1205 )
   1206 sequence_output = outputs[0]
   1207 logits = self.classifier(sequence_output)

File ~/github/contact-theory-topic/team_tools_env/lib/python3.11/site-packages/torch/nn/modules/module.py:1553, in Module._wrapped_call_impl(self, *args, **kwargs)
   1551     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1552 else:
-> 1553     return self._call_impl(*args, **kwargs)

File ~/github/contact-theory-topic/team_tools_env/lib/python3.11/site-packages/torch/nn/modules/module.py:1562, in Module._call_impl(self, *args, **kwargs)
   1557 # If we don't have any hooks, we want to skip the rest of the logic in
   1558 # this function, and just call forward.
   1559 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1560         or _global_backward_pre_hooks or _global_backward_hooks
   1561         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1562     return forward_call(*args, **kwargs)
   1564 try:
   1565     result = None

File ~/github/contact-theory-topic/team_tools_env/lib/python3.11/site-packages/transformers/models/roberta/modeling_roberta.py:798, in RobertaModel.forward(self, input_ids, attention_mask, token_type_ids, position_ids, head_mask, inputs_embeds, encoder_hidden_states, encoder_attention_mask, past_key_values, use_cache, output_attentions, output_hidden_states, return_dict)
    796 if hasattr(self.embeddings, \"token_type_ids\"):
    797     buffered_token_type_ids = self.embeddings.token_type_ids[:, :seq_length]
--> 798     buffered_token_type_ids_expanded = buffered_token_type_ids.expand(batch_size, seq_length)
    799     token_type_ids = buffered_token_type_ids_expanded
    800 else:

RuntimeError: The expanded size of the tensor (524) must match the existing size (514) at non-singleton dimension 1.  Target sizes: [1, 524].  Tensor sizes: [1, 514]"
}

**Comment by xehu** [comment]
@JamesPHoughton This Issue is to document the bug that you reported; I created the branch https://github.com/Watts-Lab/team_comm_tools/tree/james_debug to try to reproduce the bug, but things look fine on my end.

The whole pipeline completes in ~7 min on my machine without issues:

<img width="712" alt="Screenshot 2024-10-08 at 1 48 28 AM" src="https://github.com/user-attachments/assets/25669704-5002-4146-ae3d-210d8fe6a672">

Are you able to reproduce the bug with the latest release (https://pypi.org/project/team-comm-tools/) and the FeatureBuilder call in the notebook?

To protect your data's privacy, the dataset (`all_utterances.csv`) and the vector cache (`vector_data/`) are hidden from GitHub, but exist at the top level of the `james` folder.

**Comment by xehu** [comment]
[Marking as blocked due to inability to reproduce]

**Comment by JamesPHoughton** [comment]
I ran with `team_comm_tools == 0.1.4`, and didn't have this error, on the same dataset - hopefully fixed as part of the update. Probs can close, and if we see it again reopen.

**Comment by xehu** [comment]
Huh, strange! Glad it's fixed, and sorry that we don't have a more definitive answer! Closing the issue for now, but let's keep an eye out in case this is a problem again. Thank you :)
